# Generated by Django 4.2.7 on 2023-11-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=150)),
                ('date', models.DateTimeField()),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
